### ISSUE TITLE
About continue training

### ISSUE THREAD

**Issue by tangjilin** [gjy3035/C-3-Framework#13]
Can I continue training from some epoch(like epoch 100 )? It seems like the framework doesn't support this function?  Thanks.

**Comment by gjy3035** [comment]
We will finish it this weekend.
Thanks for your attention!

**Comment by tangjilin** [comment]
thx! closed

**Comment by gjy3035** [comment]
@tangjilin Training from a resume is finished. Please visit this Chinese link: https://github.com/gjy3035/C-3-Framework/issues/4#issuecomment-475098033 and clone the newest code.
