### ISSUE TITLE
关于baseline使用的基础网络结构

### ISSUE THREAD

**Issue by pxq0312** [gjy3035/C-3-Framework#15]
你好，为什么VGG16选择使用conv4_3的输出，ResNet选择使用layer3的输出呢？为什么不选择conv5_3和layer4的输出呢？也就是说，在输出feature map的深度和空间尺寸上怎么权衡呢？

**Comment by gjy3035** [comment]
首先，我们说一下这份代码的目的是，提供有效、简单的的baseline给大家。
接下来我们说说原因，如果选择更深的层来估计密度图，由于其尺寸太小，密度图质量会下降。当然可以去掉pooling或者修改stride为1，但是相应的运算量会以平方增长，我们没有过多的卡进行如此大量的计算（毕竟这个仅仅是我个人课余做的事情）。另一种进一步的方案，你也可以对baseline进行改进来作为自己的baseline，像FCN-8/16s，U Net等，结合多层网络来缓解密度图尺寸过小的问题，也能得到更好的实验结果。这就涉及到了自己对性能、速度的一个权衡了。

**Comment by pxq0312** [comment]
非常感谢！
