### ISSUE TITLE
GCC 数据集的cc cl rd是什么意思呀

### ISSUE THREAD

**Issue by xiaojiao324** [gjy3035/C-3-Framework#18]
小白不知道GCC 数据集的cc cl rd是什么意思呀，代表什么呢

**Comment by Ethanwl** [comment]
readme中写着的：GCC(rd,cc,cl) stand for GCC dataset using random/cross-camera/cross-location/ splitting, respectively.
更具体地要看论文：Learning from Synthetic Data for Crowd Counting in the Wild

**Comment by xiaojiao324** [comment]
> readme中写着的：GCC(rd,cc,cl) stand for GCC dataset using random/cross-camera/cross-location/ splitting, respectively.
> 更具体地要看论文：Learning from Synthetic Data for Crowd Counting in the Wild

**Comment by xiaojiao324** [comment]
非常感谢！
