### ISSUE TITLE
验证集与测试集

### ISSUE THREAD

**Issue by catherinezll95** [gjy3035/C-3-Framework#19]
验证集与测试集。您好，我看您的代码中，验证集即为测试集，请问验证集和测试集不用区分吗？还是因为图片数量少，所以可以用测试集当作验证集处理。

**Comment by gjy3035** [comment]
严格意义上，在没有提供验证集的数据集中，验证数据应该从训练数据中随机选取（类似于KITTI分割数据集的做法 ），或者对训练数据采取k折交叉验证的方式进行训练。
但随着DL的研究，由于训练耗时耗力，这种方式慢慢被淡化了（除非数据集明确划分验证集），加之人群计数数据集自身训练数据较少，所以很多都是直接将测试当作验证。这种现象在cifar-10分类，re-id等领域也非常常见。

**Comment by catherinezll95** [comment]
好的，谢谢您，但是我在用训练好的CSRnet测试的时候发现,验证时候是70，而测试的时候，同样的模型却是79的结果。请问如果验证集和测试集是同样的数据的话，那么两者的结果不是应该相同吗？
![Uploading 图片.png…]
![图片](https://user-images.githubusercontent.com/44294357/57577033-97b01700-74a0-11e9-824a-f65475144b97.png)

**Comment by catherinezll95** [comment]
好的，谢谢您，但是我在用训练好的CSRnet测试的时候发现,验证时候是70，而测试的时候，同样的模型却是79的结果。请问如果验证集和测试集是同样的数据的话，那么两者的结果不是应该相同吗？
![图片](https://user-images.githubusercontent.com/44294357/57577047-db0a8580-74a0-11e9-9e4a-dd41cbc10edd.png)
![图片](https://user-images.githubusercontent.com/44294357/57577050-e6f64780-74a0-11e9-91f7-f29419435460.png)

**Comment by gjy3035** [comment]
确保transforms参数与训练时相同。

**Comment by pikerbright** [comment]
@gjy3035 请问repo里是实验结果都是在test集上最优模型的结果吗？我的实验发现如果严格采用val集选择最优模型，再在test集上测试，最终结果还是要差一点的。

**Comment by gjy3035** [comment]
是。Repo这样做的目的在于结果的可复现性。
毕竟对于验证集的选择，大家会有不同的方法和随机结果。而这种现象在人群计数这类小数据集上，对实验的可复现性影响较大。
在以往我们自己的论文中，都是严格按照随机策略划分验证集。因此在GCC数据集上的性能要低于C3F的结果的（相信你通过对比也可以发现）。
这样做性能差一些的原因是，我们无法保证所选取的验证集跟测试集的分布完全一致。

综上，为确保实验数据、参数一致情况下的复现，我们在repo中将测试当成了验证集。关于这一点我们在昨天刚刚发布的中文介绍（https://mp.weixin.qq.com/s/zUcLZ41mse7qRqZgXlMvvg）里的Q&A部分也有回答。

**Comment by wsz1029** [comment]
您好，仅针对人群计数这个任务来说，如果我直接拿测试集当验证集，这样得到的结果虽然好，但是在学术上是否有过拟合测试集的嫌疑？

**Comment by hellowangqian** [comment]
我觉得大部分情况下拿测试集当验证集都会造成过拟合，得到”过于好”的结果，除非模型本身非常稳定。建议用训练集作为验证集，现在大部分方法都是基于patch的训练，验证时可以选出一部分或全部训练图片，整张测试
