### ISSUE TITLE
关于CMTL的复现问题。

### ISSUE THREAD

**Issue by gjy3035** [gjy3035/C-3-Framework#2]
@SelinaFelton 

对于CMTL的复现，代码我已经检查完成。很遗憾，在尝试了多组参数后，网络依然无法收敛。

之前我也遇到过pytorch0.2的回归网络在0.3及其以上版本中无法收敛的问题。你可以尝试使用[CMTL的初始化代码](https://github.com/svishwa/crowdcount-cascaded-mtl/blob/master/src/network.py)，对网络进行初始化操作。

也可以暂时分类loss权重置零，仅仅训练回归网络。如果有问题，可以继续在这里讨论。

**Comment by monckxqq** [comment]
请问下，CMTL的代码现在是什么状态了？我试了一下，好像还是不能收敛到benchmark的水平，MAE/MSE只能到200/300的样子？
