### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by koalaofpoint** [gjy3035/C-3-Framework#20]
Sir,I use the framework to train vgg model and SHHB,but 1000 epochs take three days. I don't know what happened？I don't modify anything

**Comment by wwwzxoe303com** [comment]
@koalaofpoint The training time is determined by your GPU. My GPU (single 1080Ti) trained SHB about 500 epoches, which takes about 4 hours in my memory. Maybe you can check volatile gpu-util in terminal.
