### ISSUE TITLE
about issues in single gpu training

### ISSUE THREAD

**Issue by homurajiang** [gjy3035/C-3-Framework#22]
When I ues CSRNet to train with single GPU, I meet the error of this :
self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CrowdCounter:
	Missing key(s) in state_dict: "CCN.frontend.0.bias", "CCN.frontend.0.weight", "CCN.frontend.2.bias", "CCN.frontend.2.weight", "CCN.frontend.5.bias", "CCN.frontend.5.weight", "CCN.frontend.7.bias", "CCN.frontend.7.weight", "CCN.frontend.10.bias", "CCN.frontend.10.weight", "CCN.frontend.12.bias", "CCN.frontend.12.weight", "CCN.frontend.14.bias", "CCN.frontend.14.weight", "CCN.frontend.17.bias", "CCN.frontend.17.weight", "CCN.frontend.19.bias", "CCN.frontend.19.weight", "CCN.frontend.21.bias", "CCN.frontend.21.weight", "CCN.backend.0.bias", "CCN.backend.0.weight", "CCN.backend.2.bias", "CCN.backend.2.weight", "CCN.backend.4.bias", "CCN.backend.4.weight", "CCN.backend.6.bias", "CCN.backend.6.weight", "CCN.backend.8.bias", "CCN.backend.8.weight", "CCN.backend.10.bias", "CCN.backend.10.weight", "CCN.output_layer.bias", "CCN.output_layer.weight". 
	Unexpected key(s) in state_dict: "er", "ecord", "e", "", "h". 

How to fix this? thank you

**Comment by gjy3035** [comment]
The weight is a python dict in fact. You can directly rename the key. This is an example:
```
import torch
wts = torch.load('xxx.pth')
new_wts = {}
for i_key in wts.keys():
    print i_key[4:len(i_key)]
    new_wts[i_key[4:len(i_key)]] = wts[i_key]
torch.save(new_wts,'new_xxx.pth')
```

You maybe modify some index according to your need.
