### ISSUE TITLE
Some questions about the spatial encoder

### ISSUE THREAD

**Issue by haoxuhao** [gjy3035/C-3-Framework#24]
@gjy3035 
hi gjy3035,
 
As far as I know, the spatial encoder is first applied in lane detection because of the consistency in spatial. Can you tell me some beneficial effect of this encoder applied in this crowd density estimation case? thanks.

**Comment by gjy3035** [comment]
Our paper about spatial encoder is coming soon, which is accepted by T-CSVT in May, The code is available at  https://github.com/gjy3035/PCC-Net.

**Comment by haoxuhao** [comment]
ok, thank you for your immediate reply
