### ISSUE TITLE
直接使用图片太大

### ISSUE THREAD

**Issue by GChen-ai** [gjy3035/C-3-Framework#44]
您好，在参考您的代码时，如果我选择了参数量较大的模型，直接送入整张图片会有很大的计算开销，您是否考虑过将图片切片的方式呢？或者有什么更好的解决方案吗
感谢

**Comment by gjy3035** [comment]
切片，resize，或者换小模型。

**Comment by lq0104** [comment]
@gjy3035 那再请问一下，有些图像分辨率非常大，训练的时候可以crop，验证的时候怎么做呢？
当然验证的时候也可以crop，但我想问的是业界的通常做法，他们在发paper时用的是crop的方式吗？还是有其他更好、更通用的方式呢？
