### ISSUE TITLE
勘误：C3F technical report 

### ISSUE THREAD

**Issue by PuddingCoder** [gjy3035/C-3-Framework#46]
第2.1节中，

> More processing details are displayed in Table 2.

应该是Table 1吧

另外有些不太清楚的地方。生成密度图中的kennel size 是什么意思。是生成密度图时，高斯核函数的参数吗？还是说一个人头在原图分辨率中表示为一个15*15的大小？

**Comment by gjy3035** [comment]
1. 我们会尽快修改。
2. kernel size指的是，生成密度图时，高斯核的参数。

万分感谢！
