### ISSUE TITLE
Problem about GTScaleDown

### ISSUE THREAD

**Issue by GChen-ai** [gjy3035/C-3-Framework#57]
I found that function may lead to some negative numbers. Are there some difference between using prepare.m and using this function?

**Comment by gjy3035** [comment]
do you use CSR? it dose not use relu in the last conv layer, so it may produce the negative density values.

**Comment by GChen-ai** [comment]
I don't mean the output of the network. If I use GTScaleDown to transform the density map, the density map may have some negative values.

**Comment by gjy3035** [comment]
Can you provide more detailed information?

**Comment by GChen-ai** [comment]
After using GTScaleDown to transform the ground truth, there will appear some negative values. Maybe it's because of downsampling? You could try to compare them.
