### ISSUE TITLE
Resuming training - KeyError 'net'

### ISSUE THREAD

**Issue by hi-ilkin** [gjy3035/C-3-Framework#58]
I  want to continue training using SHHB and VGG, so I changed these lines at config.py

`__C.DATASET = 'SHHB' 
__C.RESUME = True  # contine training
__C.RESUME_PATH = 'pretrained_models/03-VGG_all_ep_32_mae_36.6_mse_88.9.pth'  `

But I got following error at trainer.py :

>     self.net.load_state_dict(latest_state['net'])
> KeyError: 'net'

**Comment by gjy3035** [comment]
you should load the 'latest_state.pth' instead of the weight model.

__C.RESUME_PATH = " path to 'latest_state.pth' "

**Comment by hi-ilkin** [comment]
Are they available ?
