### ISSUE TITLE
How to get the gt label using python?

### ISSUE THREAD

**Issue by FanShuixing** [gjy3035/C-3-Framework#68]
Hello,Thanks for your work.I want to use this code for my own object detection datasets.The first , I find the center of object detection datasets and generate mat file using python, which step is simple.The second ,I used your code datasets/SHHB/prepare_SHHB.m to generate csv file which is the model need for training. Finally ,I get a good result .However ,Using matlab is not simple for me. Do you have any suggestions to generate csv file with python?

**Comment by gjy3035** [comment]
https://github.com/gaoguangshuai/survey-for-crowd-counting/tree/master/Python-script

**Comment by FanShuixing** [comment]
Thanks! I also found this script and used it.

**Comment by BJTUJia** [comment]
@FanShuixing Hi there, sorry to bother you. I also want to use this project on my own dataset, but I am having some trouble generating the ground_truth .mat files. Can you kindly show me how you do this? Thanks very much!

**Comment by Flyooofly** [comment]
> Hello,Thanks for your work.I want to use this code for my own object detection datasets.The first , I find the center of object detection datasets and generate mat file using python, which step is simple.The second ,I used your code datasets/SHHB/prepare_SHHB.m to generate csv file which is the model need for training. Finally ,I get a good result .However ,Using matlab is not simple for me. Do you have any suggestions to generate csv file with python?

你好，可以咨询一下第一步是如何生成.mat文件的吗？非常感谢！

**Comment by Flyooofly** [comment]
> @FanShuixing Hi there, sorry to bother you. I also want to use this project on my own dataset, but I am having some trouble generating the ground_truth .mat files. Can you kindly show me how you do this? Thanks very much!

你好，可以咨询一下第一步是如何生成.mat文件的吗？非常感谢

**Comment by Flyooofly** [comment]
> Thanks! I also found this script and used it.

你好，可以咨询一下第一步是如何生成.mat文件的吗？非常感谢

**Comment by Flyooofly** [comment]
> @FanShuixing你好，打扰你了。我也想在我自己的数据集上使用这个项目，但是我在生成 ground_truth .mat 文件时遇到了一些问题。你能告诉我你是怎么做到的吗？非常感谢！

你好，可以咨询一下第一步是如何生成.mat文件的吗？非常感谢

**Comment by Flyooofly** [comment]
> https://github.com/gaoguangshuai/survey-for-crowd-counting/tree/master/Python-script

你好，可以咨询一下第一步是如何生成.mat文件的吗？非常感谢

**Comment by FCgogogo** [comment]
你好，可以咨询一下第一步是如何生成.mat文件的吗？非常感谢
