### ISSUE TITLE
how to get the coordinate from predict heatmaps?

### ISSUE THREAD

**Issue by FanShuixing** [gjy3035/C-3-Framework#76]
Hi,Thanks for your work.I have get good result using this project. Then I want to know the coordinate of the keypoint. It's easy to know this coordinate from gt heatmap as there is only one max value in gt heatmap, but the predict heatmap has many max value for each keypoint. I can't find coordinate of this keypoints.
Do you have some suggestions ,or any paper  you suggest  reading?

**Comment by gjy3035** [comment]
C3F focuses on density estimation. If you want to get the location map from the density map, you maybe use GPR in this paper: https://arxiv.org/abs/1912.03677

If you want to tackle crowd localization, you should follow RAZNet (CVPR2019). 
Or, you can also wait for us to release our baseline for crowd localization in NWPU-Crowd dataset (in 3 months).

**Comment by FanShuixing** [comment]
Thanks! I will read these papers for now, and I also expect your release.
