### ISSUE TITLE
请问：1.LOG_PARA参数指什么，为什么那么每张图片求和后要除以它？2.可以简单描述一下标签归一化作用么！？谢谢！

### ISSUE THREAD

**Issue by chinayb** [gjy3035/C-3-Framework#8]
请问：1.LOG_PARA参数指什么，为什么那么每张图片求和后要除以它？2.可以简单描述一下标签归一化作用么！？谢谢！

**Comment by gjy3035** [comment]
参见这条回答:
https://github.com/gjy3035/C-3-Framework/issues/5#issuecomment-476461493

**Comment by chinayb** [comment]
之前没看到其他问题，非常感谢！

**Comment by gjy3035** [comment]
我们在中文博客对这个问题做了一些实验对比，参见：https://zhuanlan.zhihu.com/p/65650998
