### ISSUE TITLE
How to get the ground_truth location .mat files?

### ISSUE THREAD

**Issue by BJTUJia** [gjy3035/C-3-Framework#83]
@gjy3035 Dear author, thanks a lot for this nice repo. I want to use it on my recent project that aims to count the number of animals. I have downloaded images from the internet, but I am struggling to get the ground truth files that are provided along with the person crowd datasets like SHHB.  Any chance you know how this mat files are generated? Like a tool or scripts?
I am quite new to this field, any help from you is highly appreciated! Thanks a lot!

**Comment by Ronpie** [comment]
Hi @BJTUJia 
In my opinion, the way people are doing there .mat file by hand, it is the bounding box surrounding human head in SHHB dataset. Or you can find some ML model that can detect that target you want to generate these bounding box, and then you checking the result and add the missing bounding box data to the file.

Hope this can help you

**Comment by BJTUJia** [comment]
@Ronpie Thanks，we are annotating the images by hand now. Thanks for your answer!
