### ISSUE TITLE
Asking MEAN_STD value apply for each type of dataset before trainning

### ISSUE THREAD

**Issue by Ronpie** [gjy3035/C-3-Framework#86]
Hi @gjy3035 ,

Thank you for sharing this really helpful framework and the experimental results.

I have some question about how you processed data on each dataset before training.

Can I know why you apply a littte different method to generate the density_map for each dataset, Is it okay if I apply the same for all the dataset. 

One more question is about the MEAN_STD in setting.py of each datasets, Can I know how you calculate that number? I have calculated base on this pytorch example but get the results is really far from you on SHHB dataset.  (https://github.com/wenwei202/pytorch-examples/blob/autogrow/cifar10/get_mean_std.py). With result on train set std  = [1.0160, 1.0153, 1.0140]

Many thank, 

Ron

**Comment by MagazzuGaetano** [comment]
I think it should be done here ./misc/cal_mean.py

my results for SHHB:
means: [0.45158013701438904, 0.44690969586372375, 0.4314986765384674]
stdevs: [0.23733630776405334, 0.22954222559928894, 0.2260865569114685]

repo results for SHHB:
means: [0.452016860247, 0.447249650955, 0.431981861591]
stdevs: [0.23242045939, 0.224925786257, 0.221840232611])

**Comment by Ronpie** [comment]
@MagazzuGaetano,
Ah, I got it, after running the code
I got result for SHHB training folder: 
means: [0.45157715678215027, 0.4469097852706909, 0.43149933218955994]
stdevs: [0.23733612895011902, 0.2295425534248352, 0.2260863184928894]

But as I read yesterday, there need to be run on the whole dataset or at least a whole part of it to calculate the mean and stdevs: 
Then my results is:
means: [0.4461599886417389, 0.4418756663799286, 0.42691317200660706]
stdevs: [0.2374626249074936, 0.2295616865158081, 0.22606471180915833]
Do you have any idea about this? 

Also thank you for your helping.

**Comment by Ronpie** [comment]
Ah I have gotten the answer for this.
