### ISSUE TITLE
How to visualize the density map? 

### ISSUE THREAD

**Issue by BJTUJia** [gjy3035/C-3-Framework#87]
Dear author, thanks for this excellent repo. I am having some trouble with the visualization of density map. Say, if I have got the density map using matlab codes: im_density = get_density_map_gaussian(im,annPoints,15,4); how to draw the density maps like the ones in the papers? I've tried some matlab codes, the outputs are all weird...
![image](https://user-images.githubusercontent.com/24791613/84976322-2a1df200-b15a-11ea-8940-c8b3820a46fe.png)

**Comment by gjy3035** [comment]
matlab:
imsgesc(density_map)

**Comment by BJTUJia** [comment]
Thank you very much!  For others who might be interested, I find that imshow(im_density,[]); colormap(gca, jet); has the same effect.  Thanks again!@gjy3035

I will close this issue now.
