### ISSUE TITLE
About the test of SANet

### ISSUE THREAD

**Issue by tangjilin** [gjy3035/C-3-Framework#9]
How do you realize the test process of SANet? Can you  provider the code for patch-based test？ Thanks!

**Comment by gjy3035** [comment]
你好，关于SANet的测试，由于我一直无法确定是否能正确理解作者的原意，加之效果并不明显，因此没有提供代码。
我的理解从滑窗角度来说，可以这样描述：
采用原图大小的1/4 高, 1/4宽的滑窗，从左上方开始滑动，在水平方向上的步长为1/8宽，在竖直方向上，步长为1/8高，这样能够保证原论文中的50%面积覆盖。
对于重叠区域的密度值选取，计算该点在不同patch中的位置，选择离中心点最近的一个patch作为最终的密度值。

原文内容：
> For testing the model trained based on patches, we crop each test sample to patches 1/4 size of original image with 50% overlapping. For each overlapping pixels between patches, we only reserve the density value in the patch of which the center is the nearest to the pixel than others, because the center part of patches has enough contextual information to ensure accurate estimation.

**Comment by tangjilin** [comment]
@gjy3035 好的，了解了，谢谢解答!
